export const repoData = [
  'https://api.github.com/repos/Afiffudin-au/beatiful-photos/languages',
  'https://api.github.com/repos/Afiffudin-au/air-bnb-c/languages',
  'https://api.github.com/repos/Afiffudin-au/CookRecipe-zz/languages',
  'https://api.github.com/repos/Afiffudin-au/crypto-market-zz/languages',
  'https://api.github.com/repos/Afiffudin-au/Css-Alignment/languages',
  'https://api.github.com/repos/Afiffudin-au/E-commerce-made-in-home/languages',
  'https://api.github.com/repos/Afiffudin-au/endstock-zz/languages',
  'https://api.github.com/repos/Afiffudin-au/fitness-array/languages',
  'https://api.github.com/repos/Afiffudin-au/Generate_Random_Name_Fun/languages',
  'https://api.github.com/repos/Afiffudin-au/icon-finder-zz/languages',
  'https://api.github.com/repos/Afiffudin-au/ImageGallery/languages',
  'https://api.github.com/repos/Afiffudin-au/ip-lookup-zz/languages',
  'https://api.github.com/repos/Afiffudin-au/IP_Subnetting/languages',
  'https://api.github.com/repos/Afiffudin-au/Jquery-AJAX-CORONA-VIRUS-API/languages',
  // 'https://api.github.com/repos/Afiffudin-au/Landing-pages/languages',
  // 'https://api.github.com/repos/Afiffudin-au/Landing_page/languages',
  // 'https://api.github.com/repos/Afiffudin-au/Landing_page_2.github.io/languages',
  'https://api.github.com/repos/Afiffudin-au/movie-zz-v2/languages',
  'https://api.github.com/repos/Afiffudin-au/movie-zz-v2-next-ts/languages',
  'https://api.github.com/repos/Afiffudin-au/Movies-ZZ/languages',
  'https://api.github.com/repos/Afiffudin-au/icon-zz-ts/languages',
  'https://api.github.com/repos/Afiffudin-au/Proxy-server-Icon-Finder-API/languages',
  'https://api.github.com/repos/Afiffudin-au/Rand.github.io/languages',
  'https://api.github.com/repos/Afiffudin-au/random-image.github.io/languages',
  'https://api.github.com/repos/Afiffudin-au/Simple-social/languages',
  'https://api.github.com/repos/Afiffudin-au/spotify-clone/languages',
  'https://api.github.com/repos/Afiffudin-au/TypeScript-array/languages',
  'https://api.github.com/repos/Afiffudin-au/VANILLA-JS-CORONA-API/languages',
  'https://api.github.com/repos/Afiffudin-au/videos-zz/languages',
  'https://api.github.com/repos/Afiffudin-au/wallpaper-zz/languages',
  'https://api.github.com/repos/Afiffudin-au/zz-icon/languages',
  'https://api.github.com/repos/Afiffudin-au/portfolio/languages',
  'https://api.github.com/repos/Afiffudin-au/Color_Running_Fun_Fun/languages',
]
